apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: global-lgentsvr
  namespace: global
  labels:
    app: lgentsvr
    component: global-lgentsvr
spec:
  selector:
    matchLabels:
      app: lgentsvr
      component: global-lgentsvr
  template:
    metadata:
      labels:
        app: lgentsvr
        component: global-lgentsvr
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 3.96.0.10
        searches:
          - global.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: '5'
      hostNetwork: true
      containers:
        - name: global-lgentsvr
          image: lgentsvr:develop
          lifecycle:
            postStart:
              exec:
                command: ["/opt/lgentsvr/cp-file.sh"]
            preStop:
              exec:
                command:
                  - "pkill lgentsvr"
          env:
            - name: MODE
              value: lgentsvr
            - name: APP_NAME
              value: global-lgentsvr
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EnvParameter
              value: "-f /opt/lgentsvr/conf/conf.d/config.ini"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          resources:
            requests:
              memory: 0.5Gi
              cpu: '500m'
            limits:
              memory: 8Gi
              cpu: '8000m'
          ports:
            - containerPort: 8400
              name: lgentsvr-port
              protocol: TCP
          startupProbe:
            failureThreshold: 60
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8400
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8400
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 8400
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: config-path
              mountPath: /opt/lgentsvr/conf/conf.d
            - name: localtime
              mountPath: /etc/localtime
            # - name: global-lgentsvr-install
            #   mountPath: /opt/lgentsvr/data/install
            # - name: global-lgentsvr-package
            #   mountPath: /opt/lgentsvr/data/package
      volumes:
        - name: config-path
          configMap:
            name: lgentsvr-cm
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        # - name: global-lgentsvr-install
        #   hostPath:
        #     path: AiLogAuditorlgentsvrPath/install/
        # - name: global-lgentsvr-package
        #   hostPath:
        #     path: AiLogAuditorlgentsvrPath/package/
---
apiVersion: v1
kind: Service
metadata:
  name: global-lgentsvr-svc
  namespace: global
  labels:
    app: lgentsvr-svc
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - name: global-lgentsvr-server
      protocol: TCP
      port: 8400
      targetPort: 8400
  selector:
    app: lgentsvr
    component: global-lgentsvr
