apiVersion: batch/v1
kind: Job
metadata:
  name: saas-upgrade
  namespace: saas
  labels:
    app: saas
    component: saas-upgrade
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: saas
        component: saas-upgrade
    spec:
      restartPolicy: Never
      serviceAccountName: saas-user
      containers:
        - name: saas-upgrade
          image: core.harbor1.domain/soc/saas:upgrade-d539b35f8
          args: ["upgrade"]
          env:
            - name: APP_NAME
              value: saas-upgrade
            - name: JAVA_OPTS
              value: -Xms2G -Xmx6G -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=512m -XX:+UseCompressedOops  -Dfastjson.parser.safeMode=true  -Djava.awt.headless=true
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: saas-upgrade-config-volume
              mountPath: /opt/saas/conf/conf.d
            - name: ssh-path
              mountPath: /root/.ssh
      volumes:
        - name: saas-upgrade-config-volume
          configMap:
            name: saas-config
        - name: ssh-path
          hostPath:
            path: /root/.ssh