apiVersion: v1
kind: ConfigMap
metadata:
  name: webui-config
  namespace: saas
  labels:
    app: saas
data:
  nginx.conf: |+
      client_max_body_size 122880M;
      client_header_timeout 1800;
      client_body_timeout 1800;
      add_header Set-Cookie "Path=/; HttpOnly; Secure; SameSite=Lax";
      add_header X-Frame-Options "SAMEORIGIN";
      add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
      expires 356d;
      server_tokens off;

      gzip  on;
      gzip_min_length 1k;
      gzip_comp_level 3;
      gzip_buffers 4 16k;
      gzip_proxied any;
      gzip_vary on;
      gzip_static on;
      gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
      gzip_disable "MSIE [1-6]\.";
      
      server {
        listen 80;
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
          set $fallback_file /index.html;
          if ($http_accept !~ text/html) {
           set $fallback_file /null;
          }
          try_files $uri $fallback_file;
        }
        location ~/api/ {
          proxy_pass  http://saas-web.saas.svc.cluster.local;
          proxy_read_timeout 1800s;
          proxy_send_timeout 1800s;
          proxy_connect_timeout 5s;
        }
        location = /api/status {
          proxy_pass  http://saas-web.saas.svc.cluster.local/monitor/health;
          proxy_connect_timeout 5s;
        }
        location ~ /c/ {
          proxy_pass  http://saas-receiver-http.saas.svc.cluster.local;
          proxy_read_timeout 600s;
          proxy_send_timeout 600s;
          proxy_connect_timeout 120s;
        }
        location ~ ^/healthcheck {
          default_type text/html;
          return 200 'ok!';
          access_log /var/log/nginx/health_access.log main;
        }
      }