apiVersion: v1
kind: Service
metadata:
  name: zinc
  namespace: monitor
spec:
  type: NodePort
  selector:
    app: zinc
  ports:
  - name: http
    port: 4080
    targetPort: 4080
    nodePort: 44080
---
# create statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zinc
  namespace: monitor
  labels:
    name: zinc
spec:
  serviceName: zinc
  replicas: 1
  selector:
    matchLabels:
      name: zinc
      app: zinc
  template:
    metadata:
      labels:
        name: zinc
        app: zinc
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      # terminationGracePeriodSeconds: 0
      containers:
        - name: zinc
          image: zinc:latest
          env:
            - name: ZINC_FIRST_ADMIN_USER
              value: admin
            - name: ZINC_FIRST_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zinc-secret
                  key: psd
            - name: ZINC_DATA_PATH
              value: /go/bin/data
            - name: ZINC_PORT
              value: "4080" 
            - name: ZINC_TELEMETRY
              value: "false" 
            - name: GIN_MODE
              value: release
          #command: ["/bin/bash", "-c", "while true; do sleep 1; done"]
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 6
              memory: 12Gi
            requests:
              cpu: 32m
              memory: 50Mi
          ports:
            - containerPort: 4080
              name: http
          volumeMounts:
          - name: data
            mountPath: /go/bin/data
          - name: timezone
            mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi