apiVersion: v1
kind: Service
metadata:
  name: monitor-kafka-manager
  namespace: monitor
  labels:
    app: monitor
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9000
      nodePort: 49999
  selector:
    app: monitor
    component: monitor-kafka-manager