---
- name: Restart docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Restart containerd service
  systemd:
    name: containerd
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Restart crond service
  systemd:
    name: crond
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Restart chronyd service
  systemd:
    name: chronyd
    daemon_reload: yes
    state: restarted
    enabled: yes